---
title: "DASC 1104 Project Proposal"
author: "Ben Marlow"
date: "12/1/2020"
output: pdf_document
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<div id="my-blog-link" class="section level2">
<h2>1 My blog link</h2>
<p>My blog is available at <a href="">https://dasc-1104-bmarlow.netlify.app/</a></p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.2.1     ✓ purrr   0.3.3
## ✓ tibble  2.1.3     ✓ dplyr   0.8.3
## ✓ tidyr   1.0.0     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.4.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>dat_nfl &lt;- read.csv(file = here::here(&quot;data&quot;, &quot;nfl_elo_latest.csv&quot;))
dat_mlb &lt;- read.csv(file = here::here(&quot;data&quot;, &quot;mlb_elo_latest.csv&quot;))
glimpse(dat_nfl)</code></pre>
<pre><code>## Observations: 269
## Variables: 30
## $ date           &lt;fct&gt; 2020-09-10, 2020-09-13, 2020-09-13, 2020-09-13, 2020-0…
## $ season         &lt;int&gt; 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, …
## $ neutral        &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ playoff        &lt;fct&gt; , , , , , , , , , , , , , , , , , , , , , , , , , 
## $ team1          &lt;fct&gt; KC, JAX, CAR, BAL, BUF, MIN, DET, ATL, NE, WSH, CIN, N…
## $ team2          &lt;fct&gt; HOU, IND, OAK, CLE, NYJ, GB, CHI, SEA, MIA, PHI, LAC, …
## $ elo1_pre       &lt;dbl&gt; 1664.847, 1438.503, 1417.736, 1638.431, 1511.355, 1571…
## $ elo2_pre       &lt;dbl&gt; 1527.930, 1482.655, 1437.326, 1440.533, 1458.063, 1582…
## $ elo_prob1      &lt;dbl&gt; 0.7617556, 0.5299664, 0.5649799, 0.8195586, 0.6639485,…
## $ elo_prob2      &lt;dbl&gt; 0.2382444, 0.4700336, 0.4350201, 0.1804414, 0.3360515,…
## $ elo1_post      &lt;dbl&gt; 1676.666, 1457.867, 1399.166, 1649.702, 1526.649, 1543…
## $ elo2_post      &lt;dbl&gt; 1516.111, 1463.290, 1455.895, 1429.262, 1442.769, 1609…
## $ qbelo1_pre     &lt;dbl&gt; 1651.215, 1392.057, 1416.302, 1628.808, 1532.806, 1544…
## $ qbelo2_pre     &lt;dbl&gt; 1497.454, 1518.204, 1461.437, 1499.694, 1451.147, 1555…
## $ qb1            &lt;fct&gt; Patrick Mahomes, Gardner Minshew, Teddy Bridgewater, L…
## $ qb2            &lt;fct&gt; Deshaun Watson, Philip Rivers, Derek Carr, Baker Mayfi…
## $ qb1_value_pre  &lt;dbl&gt; 239.69530, 121.75534, 155.17461, 262.05705, 153.17524,…
## $ qb2_value_pre  &lt;dbl&gt; 195.6158, 155.6245, 181.3636, 130.9706, 134.1210, 176.…
## $ qb1_adj        &lt;dbl&gt; 6.9428086, -8.6510635, 11.8543782, 17.7484615, 0.60061…
## $ qb2_adj        &lt;dbl&gt; 3.6326586, 6.9773865, 4.4939299, -3.5942770, 5.1901076…
## $ qbelo_prob1    &lt;dbl&gt; 0.7519609, 0.3520553, 0.5041818, 0.7432960, 0.6547578,…
## $ qbelo_prob2    &lt;dbl&gt; 0.2480391, 0.6479447, 0.4958182, 0.2567040, 0.3452422,…
## $ qb1_game_value &lt;dbl&gt; 250.96437, 216.97903, 221.33934, 363.49393, 380.75142,…
## $ qb2_game_value &lt;dbl&gt; 163.113859, 266.985431, 247.800792, 64.243357, 93.6472…
## $ qb1_value_post &lt;dbl&gt; 240.82220, 131.27771, 161.79108, 272.20074, 175.93286,…
## $ qb2_value_post &lt;dbl&gt; 192.3656, 166.7606, 188.0073, 124.2978, 130.0736, 207.…
## $ qbelo1_post    &lt;dbl&gt; 1663.567, 1420.368, 1400.051, 1645.369, 1548.567, 1519…
## $ qbelo2_post    &lt;dbl&gt; 1485.102, 1489.893, 1477.688, 1483.133, 1435.386, 1580…
## $ score1         &lt;int&gt; 34, 27, 30, 38, 27, 34, 23, 25, 21, 27, 13, 34, 20, 20…
## $ score2         &lt;int&gt; 20, 20, 34, 6, 17, 43, 27, 38, 11, 17, 16, 23, 24, 17,…</code></pre>
<pre class="r"><code>glimpse(dat_mlb)</code></pre>
<pre><code>## Observations: 951
## Variables: 26
## $ date         &lt;fct&gt; 2020-10-27, 2020-10-25, 2020-10-24, 2020-10-23, 2020-10-…
## $ season       &lt;int&gt; 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 20…
## $ neutral      &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
## $ playoff      &lt;fct&gt; w, w, w, w, w, w, l, l, l, l, l, l, l, l, l, l, l, l, l,…
## $ team1        &lt;fct&gt; LAD, TBD, TBD, TBD, LAD, LAD, LAD, TBD, LAD, ATL, TBD, A…
## $ team2        &lt;fct&gt; TBD, LAD, LAD, LAD, TBD, TBD, ATL, HOU, ATL, LAD, HOU, L…
## $ elo1_pre     &lt;dbl&gt; 1607.758, 1566.450, 1563.862, 1567.099, 1608.352, 1604.6…
## $ elo2_pre     &lt;dbl&gt; 1564.178, 1605.486, 1608.074, 1604.836, 1563.583, 1567.3…
## $ elo_prob1    &lt;dbl&gt; 0.5828511, 0.4256515, 0.4159707, 0.4280914, 0.5850682, 0…
## $ elo_prob2    &lt;dbl&gt; 0.4171489, 0.5743485, 0.5840293, 0.5719086, 0.4149318, 0…
## $ elo1_post    &lt;dbl&gt; 1610.046, 1564.178, 1566.450, 1563.862, 1604.836, 1608.3…
## $ elo2_post    &lt;dbl&gt; 1561.890, 1607.758, 1605.486, 1608.074, 1567.099, 1563.5…
## $ rating1_pre  &lt;dbl&gt; 1610.723, 1564.204, 1562.244, 1564.613, 1611.701, 1609.3…
## $ rating2_pre  &lt;dbl&gt; 1562.805, 1609.323, 1611.284, 1608.914, 1561.827, 1564.2…
## $ pitcher1     &lt;fct&gt; Tony Gonsolin, Tyler Glasnow, Ryan Yarbrough, Charlie Mo…
## $ pitcher2     &lt;fct&gt; Blake Snell, Clayton Kershaw, Julio Urias, Walker Buehle…
## $ pitcher1_rgs &lt;dbl&gt; 54.05579, 52.96693, 52.63655, 57.97116, 54.97549, 56.730…
## $ pitcher2_rgs &lt;dbl&gt; 54.53445, 57.21495, 50.97410, 55.93798, 54.42156, 53.858…
## $ pitcher1_adj &lt;dbl&gt; 7.9957421, -1.8267342, -3.9595166, 20.5465884, 13.013222…
## $ pitcher2_adj &lt;dbl&gt; 6.0400241, 23.1140964, -6.2048839, 18.0984217, 4.0097101…
## $ rating_prob1 &lt;dbl&gt; 0.5945472, 0.3687158, 0.4111612, 0.4203756, 0.6110917, 0…
## $ rating_prob2 &lt;dbl&gt; 0.4054528, 0.6312842, 0.5888388, 0.5796244, 0.3889083, 0…
## $ rating1_post &lt;dbl&gt; 1612.374, 1562.805, 1564.204, 1562.244, 1608.914, 1611.7…
## $ rating2_post &lt;dbl&gt; 1561.153, 1610.723, 1609.323, 1611.284, 1564.613, 1561.8…
## $ score1       &lt;int&gt; 3, 2, 8, 2, 4, 8, 4, 4, 3, 3, 4, 10, 4, 4, 3, 2, 7, 1, 4…
## $ score2       &lt;int&gt; 1, 4, 7, 6, 6, 3, 3, 2, 1, 7, 7, 2, 3, 3, 15, 5, 8, 5, 2…</code></pre>
</div>
<div id="the-impact-of-the-qb-in-the-modern-day-nfl" class="section level2">
<h2>2 The Impact of the QB in the Modern Day NFL</h2>
<p>Using data available on GitHub from FiveThirtyEight.com, I am going to examine the NFL and MLB Elo datasets. A few key variables in the NFL data include the final score of both teams in their respective games, the quarterback elo and value ratings before and after the game, and the elo win probability for either team. When looking at the MLB data, variables to heavily consider here are as follows: runs scored for both teams, the starting pitchers in each game, their team’s elo rating, and adjusted pitcher rating. There are 269 observations of 30 variables in the most recent NFL dataset and 951 observations of 26 variables in the MLB dataset.</p>
<p>Question 1:</p>
</div>
